#!/usr/bin/python

# TODOS:
#  - allow DynamoDB to be used as a meta-data service
#  - encrypt etcd usage
#  - add tests!

from __future__ import print_function
import argparse
import os
import sys
import signal
import time
import subprocess
import socket
import tempfile
import traceback
import urllib
import requests
import boto3
import json



# lets setup stdout to not have any write buffer
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)



class Toolkit(object):
    """docstring for Toolkit"""

    def __init__(self, config):
        super(Toolkit, self).__init__()
        self.config = config


    def monitor_response(self):
        try:
            return requests.get(self.config.monitor_url)
        except (requests.exceptions.Timeout, socket.timeout, requests.exceptions.ConnectionError):
            # Maybe set up for a retry, or continue in a retry loop
            r = requests.Response()
            r.status_code = 408
            return r


    def unregister_service(self):
        requests.delete(self.config.etcd_service_key_url())


    def register_service(self, ttl):
        etcd_service_value   = {'host': self.config.service_id, 'label': self.config.label, 'ip': self.config.host_ip}
        if hasattr(self.config, 'service_info'):
            for item in self.config.service_info:
                key, value = item.split('=')
                if key and value:
                    etcd_service_value[key] = value
        requests.put(self.config.etcd_service_key_url(), {'value':json.dumps(etcd_service_value), 'ttl':ttl} )


    def acquire_lease(self, scope='', lease_holder=None):
        # print("acquire_lease ------------------------ {0} ---- {1}".format(lease_holder, self.config.service_id))
        lease_holder = lease_holder or self.config.service_id
        timeout = time.time() + self.config.acquire_timeout
        while time.time() < timeout:
            response = requests.put(self.config.etcd_lock_url(scope) + "?prevExist=false", {'value': lease_holder, 'ttl':self.config.lease_timeout} )
            if response.ok:
                return True
            response = requests.put(self.config.etcd_lock_url(scope) + '?prevValue={0}'.format(urllib.quote_plus(lease_holder)), {'value': lease_holder, 'ttl':self.config.lease_timeout} )
            if response.ok:
                return True
            time.sleep(1)
        return False


    def release_lease(self, scope='', lease_holder=None):
        # print("release_lease ------------------------ {0} ---- {1}".format(lease_holder, self.config.service_id))
        lease_holder = lease_holder or self.config.service_id
        return requests.delete(self.config.etcd_lock_url(scope) + '?prevValue={0}'.format(urllib.quote_plus(lease_holder)))


    def retrieve_certs(self):
        response = requests.get(self.config.etcd_cert_keys_url() + '?consistent=true')
        if response.ok:
            response.encoding = 'UTF-8'
            json = response.json()
            if 'nodes' in json['node']:
                private_key = (item for item in json['node']['nodes'] if item["key"] == "/config/{0}/certs/x509_private_key".format(self.config.label)).next()['value']
                cert        = (item for item in json['node']['nodes'] if item["key"] == "/config/{0}/certs/x509_certificate".format(self.config.label)).next()['value']
                return {'key': private_key, 'cert': cert, 'type': 'x509'}
        return None


    def create_x509_certs(self):
        key_tempfile, cert_tempfile = (None, None)
        hostname = '{0}_{1}'.format(Util.host_name(), os.getpid())
        # random = os.urandom(128)
        # print(random.encode('base-64'))
        # openssl pkcs12 -name test -export -in /tmp/test.crt -inkey /tmp/test.key -out /tmp/test.p12
        try:
            if self.acquire_lease('x509', hostname):
                certs = self.retrieve_certs()
                if certs and certs['key'] and certs['cert']:
                    return certs 
                key_tempfile = tempfile.NamedTemporaryFile()
                cert_tempfile = tempfile.NamedTemporaryFile()
                cmd = "openssl req -x509 -batch -nodes -newkey rsa:4096 -keyout {0} -out {1} 2>/dev/null".format(key_tempfile.name, cert_tempfile.name)
                os.system(cmd)
                private_key = key_tempfile.read()
                cert        = cert_tempfile.read()
                requests.put("{0}x509_private_key".format(self.config.etcd_cert_keys_url()), {'value': private_key} )
                requests.put("{0}x509_certificate".format(self.config.etcd_cert_keys_url()), {'value': cert} )
                return {'key': private_key, 'cert': cert, 'type': 'x509'}
            else:
                return None
        finally:
            self.release_lease('x509', hostname)
            if key_tempfile: 
                key_tempfile.close()
            if cert_tempfile:
                cert_tempfile.close()


    def hosts(self):
        response = requests.get(config.etcd_service_hosts_url() + '?recursive=true&consistent=true')
        response.encoding = 'UTF-8'
        json = response.json()
        output=[]
        if response.ok and 'nodes' in json['node']:
            for i, node in enumerate(json['node']['nodes']):
                output.append(node['key'].replace(self.config.etcd_service_hosts_path() + '/', ''))
        output.sort()
        return output


    def create_base_configs(self):
        try:
            requests.put(self.config.etcd_config_url(), {'dir':'true'} )
            requests.put(self.config.etcd_services_url(), {'dir':'true'} )
        except requests.exceptions.ConnectionError as e:
            print("failed to connect to {0}.  This is probably because the url is not accessible.".format(self.config.etcd_config_url()))
            raise e


class Config(object):

    def __init__(self, args):
        super(Config, self).__init__()
        self.__dict__.update(vars(args))
        if not hasattr(self, 'service_id') or not self.service_id:
            self.service_id = Util.host_name()
        if hasattr(self, 'label'):
            self.label = self.label.lower()
            # self.service_id = "{0}-{1}".format(self.label, self.service_id)
        if not self.host_ip:
            self.host_ip = Util.host_ip()


    def etcd_lock_url(self, scope=''):
        url = '{0}/locks/'.format(self.etcd_base_url(), self.label)
        if scope:
            url += '{0}_{1}/'.format(scope, self.label)
        else:
            url += '{0}/'.format(self.label)
        return url


    def etcd_base_url(self):
        return 'http://{0}:4001/v2/keys'.format(self.host_ip)


    def etcd_service_hosts_path(self):
        return '/services/{0}/hosts'.format(self.label)


    def etcd_service_hosts_url(self):
        return '{0}{1}'.format(self.etcd_base_url(), self.etcd_service_hosts_path())


    def etcd_service_key_url(self):
        return '{0}/{1}'.format(self.etcd_service_hosts_url(), self.host_ip)


    def etcd_cert_keys_url(self):
        return '{0}/{1}/certs'.format(self.etcd_config_url(), self.label)


    def etcd_config_url(self):
        return '{0}/config'.format(self.etcd_base_url())


    def etcd_services_url(self):
        return '{0}/services'.format(self.etcd_base_url())



class Util(object):
        
    @classmethod
    def print_msg(cls, message, file=sys.stdout):
        # os.system('systemd-cat -t "[{0}]" echo "{1}"'.format(args.label, message))
        print("[{0}] {1}".format(config.label, message), file=file)


    @classmethod
    def host_name(cls):
        import platform
        # print("host_name1: {0}".format(platform.node()))
        # print("host_name2: {0}".format(socket.gethostname()))
        # print("host_name3: {0}".format(socket.gethostbyaddr(socket.gethostname())[0]))
        return socket.gethostname()
        # if socket.gethostname().find('.')>=0:
        #     return socket.gethostname()
        # else:
        #     return socket.gethostbyaddr(socket.gethostname())[0]
        # print("host_name4: {0}".format(name))
        # print("host_name5: {0}".format(socket.getfqdn()))

        # return socket.gethostname()


    @classmethod
    def host_ip(cls):
        process = subprocess.Popen("ip address show docker0 2>/dev/null | grep 'inet ' | awk '{gsub(/\/[0-9]{2}/, \"\"); print $2}'", stdout=subprocess.PIPE, shell=True)
        host_ip = process.stdout.read().strip()
        if not host_ip:
            # # lets try general IP way
            process = subprocess.Popen("ip route show 0.0.0.0/0 | grep -Eo 'via \S+' | awk '{ print $2 }'", stdout=subprocess.PIPE, shell=True)
            host_ip = process.stdout.read().strip()
        return host_ip


    @classmethod
    def handle_exception(cls, e):
        # catastrophic error. bail.
        Util.print_msg(type(e))
        Util.print_msg(e)
        Util.print_msg(traceback.format_exc())

    @classmethod
    def parse_inputs(cls):
        parser = argparse.ArgumentParser(description='Help manage services, such as register in a discovery service, setup security certificates, and monitor a service')
        subparsers = parser.add_subparsers(dest='cmd')#(title='my title', description='my description', help='my help')

        # A watch command
        watch_parser = subparsers.add_parser('watch', help='watch for changes')
        watch_parser.set_defaults(func=watch)
        watch_parser.add_argument('--label', metavar='<LABEL>', required=True, help='General label of the Service to monitor.')
        watch_parser.add_argument('--service-id', metavar='<SERVICE-ID>', help='The specific id of the service to monitor.  It will default to <LABEL>-<HOSTNAME>')
        watch_parser.add_argument('--monitor-url', metavar='<MONITOR-URL>', required=True,
                            help='The URL to call to monitor the external process.  You can use an internally or ' + 
                                 'externally available URL, such as "http://172.17.8.101:9200", or one from a ' + 
                                 'linked container such as "http://service:9200".')
        watch_parser.add_argument('--service-info', nargs='*', default=[], help='If nothing is added, defaults to name=<SERVICE-ID>.')

        # An aquire-lease command
        lease_parser = subparsers.add_parser('acquire-lease', help='Acquire a lease to start monitoring')
        lease_parser.set_defaults(func=acquire_lease)
        lease_parser.add_argument('--label', metavar='<LABEL>',           required=True, help='General label of the Service to monitor.')
        lease_parser.add_argument('--service-id', metavar='<SERVICE-ID>', help='The specific id of the service to monitor.  It will default to <LABEL>-<HOSTNAME>')
        lease_parser.add_argument('--lease-timeout', metavar='<LEASE-TIMEOUT>',     type=int, help='How long until the lease expires', default=240)
        lease_parser.add_argument('--acquire-timeout', metavar='<ACQUIRE-TIMEOUT>', type=int, help='How long to wait for a lease to become available', default=360)

        # A hosts command
        host_parser = subparsers.add_parser('hosts', help='list hosts')
        host_parser.set_defaults(func=hosts)
        host_parser.add_argument('--label', metavar='<LABEL>', required=True, help='General label of the Service to monitor.')
        host_parser.add_argument('--wait', action='store_true', help='wait until there is at least one host returned.')

        # act as a simple docker ambassador
        #  
        # docker run --rm --name=influxdb-amb --link influxdb:service influxdb:service skippy/service_toolkit ambassador# --port=2012 --link-label=influxdb
        # docker run --rm --name=influxdb-proxy skippy/service_toolkit proxy --local-port=8086 --external-label=influxdb --external-port=8086
        #
        proxy_parser = subparsers.add_parser('proxy', help='act as an proxy')
        proxy_parser.set_defaults(func=proxy)
        proxy_parser.add_argument('--service-label', dest='label', required=True, help='The label of the service to link to')
        proxy_parser.add_argument('--local-port', required=True, help='The port to expose for linking to the service')
        proxy_parser.add_argument('--service-port', required=True, help='The label of the service to link to')

        # A cert command
        cert_parser = subparsers.add_parser('cert', help='retrieve security certificate')
        cert_parser.set_defaults(func=cert)
        cert_parser.add_argument('--label', metavar='<LABEL>', required=True, help='General label of the Service to retrieve security credentials for.')
        cert_parser.add_argument('--x509', action='store_true', help='retrieve x509 certificate and key')
        cert_parser.add_argument('--PKCS12', action='store_true', help='retrieve keystore')
        cert_parser.add_argument('--lease-timeout', metavar='<LEASE-TIMEOUT>', type=int, help='How long until the lease expires', default=240)
        cert_parser.add_argument('--acquire-timeout', metavar='<ACQUIRE-TIMEOUT>', type=int, help='How long until the lease expires', default=360)

        # #add common and OPTIONAL arguments
        for title, subparser in subparsers.choices.iteritems():
            subparser.add_argument('--backend', metavar='<BACKEND>', choices=['etcd', 'DynamoDB'])
            subparser.add_argument('--host-ip', metavar='<HOST_IP>', help='set the host_ip rather than the script guessing.')

        args = parser.parse_args()
        return args



def proxy(args):
    new_env = os.environ.copy()
    new_env['SERVICE_LABEL'] = toolkit.config.label.lower()
    new_env['LOCAL_PORT'] = toolkit.config.local_port
    new_env['SERVICE_PORT'] = toolkit.config.service_port
    process = subprocess.call(["confd", "-watch", "-verbose=true"], env=new_env)


def unregister_service(signum=None, frame=None):
    Util.print_msg("Watching {0} has been stopped".format(config.service_id))
    toolkit.unregister_service()
    sys.exit(0)


def acquire_lease(args):
    Util.print_msg("Waiting to acquire lease")
    response = toolkit.acquire_lease()
    if response:
        Util.print_msg("Acquired lease")
        sys.exit(0)
    else:
        Util.print_msg("timed out waiting to acquire lease")
        sys.exit(1)


def watch(args):
    Util.print_msg("Starting to watch")
    lease_released = False
    try:
        while True:
            if toolkit.monitor_response().ok:
                toolkit.register_service(8)
                Util.print_msg("Instance is up")
                if lease_released is False:
                    response = toolkit.release_lease()
                    if response.ok:
                        Util.print_msg("Releasing lease")
                        lease_released=True
            else:
                toolkit.unregister_service()
                Util.print_msg("Instance {0} is not running and has been unregistered".format(config.service_id))

            time.sleep(5)
    except Exception as e:
        # catastrophic error. bail.
        Util.handle_exception(e)
        sys.exit(1)


def hosts(args):
    try:
        while True:
            hosts = toolkit.hosts()
            if hosts:
                print( ','.join(str(x) for x in hosts) )
                sys.exit(0)
            elif not args.wait:
                sys.exit(0)

    except Exception as e:
        # catastrophic error. bail.
        Util.handle_exception(e)
        sys.exit(1)



def cert(args):
    try:
        certs = toolkit.retrieve_certs()
        if not (certs and certs['key'] and certs['cert']):
            if config.x509:
                certs = toolkit.create_x509_certs()
                if not certs:
                    #timed out with no luck!  exit
                    Util.print_msg("lease was not available!")
                    sys.exit(1)
            else:
                #don't know what to do!
                Util.print_msg("security method not defined!  Exiting")
                return {}
        if certs:
            print(json.dumps(certs))
            return
    except Exception as e:
        # catastrophic error. bail.
        Util.handle_exception(e)
        sys.exit(1)



############################################################################
## Run
############################################################################
# lets handle unix signals
signal.signal(signal.SIGTERM, unregister_service)
signal.signal(signal.SIGINT,  unregister_service)


args    = Util.parse_inputs()
config = Config(args)
toolkit = Toolkit(config)
toolkit.create_base_configs()


#trigger the assigned function call!
args.func(args) 



# service-toolkit cert --label=logstash --x509
# --name=ElasticSearch_Logging
# --instance_id=es_logging-1
# --lock-ttl=240
# --monitor-url=localhost:9200
# --etcd-key=/services/elasticsearch_logging/hosts/172.17.8.101
# --etcd-value='{"http_port": 9200, "transport_port": 9300, "name": "ElasticSearch_Logging-1"}'
# --docker

# docker run --rm -it --link elasticsearch_logging-1:service ubuntu:14.10 /bin/bash
# curl http://service:9200

# ip route show 0.0.0.0/0 | grep -Eo 'via \S+' | awk '{ print $2 }'
# ip route get 1.1.1.1 | grep -Eo 'via \S+' | awk '{ print $2 }'
# netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}'
